DROP TABLE IF EXISTS REIMBURSEMENTS CASCADE;

CREATE TABLE REIMBURSEMENTS (
	REIM_ID SERIAL PRIMARY KEY,
	AMOUNT NUMERIC NOT NULL,
	SUBMITTED TIMESTAMP NOT NULL,
	DESCRIPTION VARCHAR (250),
	RECEIPT BYTEA,
	RESOLVED TIMESTAMP,
	AUTHOR SERIAL REFERENCES USERS,
	RESOLVER SERIAL REFERENCES USERS,
	STATUS_ID BOOLEAN REFERENCES REIMBURSEMENT_STATUS,
	TYPE_ID NUMERIC REFERENCES REIMBURSEMENT_TYPE
);

DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR (100),
	LAST_NAME VARCHAR (100),
	USERNAME VARCHAR (50) UNIQUE,
	PASSWORD VARCHAR (50) UNIQUE,
	EMAIL VARCHAR (150) UNIQUE,
	ROLE_ID NUMERIC REFERENCES USER_ROLE
);

DROP TABLE IF EXISTS REIMBURSEMENT_STATUS CASCADE;

CREATE TABLE REIMBURSEMENT_STATUS (
	STATUS_ID BOOLEAN PRIMARY KEY,
	STATUS VARCHAR (10)
);

DROP TABLE IF EXISTS REIMBURSEMENT_TYPE CASCADE;

CREATE TABLE REIMBURSEMENT_TYPE (
	TYPE_ID NUMERIC PRIMARY KEY,
	TYPE VARCHAR (10)
);

DROP TABLE IF EXISTS USER_ROLE CASCADE;

CREATE TABLE USER_ROLE (
	USER_ROLE_ID NUMERIC PRIMARY KEY,
	USER_ROLE VARCHAR (10)
);

SELECT * FROM REIMBURSEMENTS;
SELECT * FROM USERS;
SELECT * FROM REIMBURSEMENT_STATUS;
SELECT * FROM REIMBURSEMENT_TYPE;
SELECT * FROM USER_ROLE;